name: 'Add two numbers'
description: 'Adds two numbers and returns total'
inputs:
  num1:
    description: 'First number'
    required: true
  num2:
    description: 'Second number'
    required: true
outputs:
  total:
    description: 'The total of the addition'
runs:
  using: 'composite'
  steps:
    - name: Execute addition script
      shell: bash
      run: python ${{ github.action_path }}/scripts/add.py ${{ inputs.num1 }} ${{ inputs.num2 }}
    - name: Capture output
      id: get_total
      run: echo "total=$(cat /home/runner/work/_temp/_github_output)" >> $GITHUB_OUTPUT
