# This is a basic workflow to help you get started with Actions

name: Diff extract


on:
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest 

    steps:
      # 1. Checkout the code of the pull request
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # 2. Compare the files and generate the diffs
      - name: Compare files and generate result
        run: |
          # Create a directory for the expected results
          mkdir diffs

          # Compare the files and apply changes
          for file in original files/*.strings; do
            base_name=$(basename "$file")

            # Diff the original file and the modified file in the PR
            diff -u "original files/$base_name" "modified files/$base_name" > diff_output.patch

            # Apply the patch to the original file to create the expected result
            patch "original files/$base_name" diff_output.patch -o "diffs/$base_name"
          done

      # 3. Upload the expected result as an artifact
      - name: Upload expected result
        uses: actions/upload-artifact@v3
        with:
          name: expected-result
          path: diffs/