name: Diff extract

on:
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      # 1. Checkout del código de la pull request con todo el historial
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-all: true
      
      # 2. (Opcional) Actualizar la rama main desde el origen
      - name: Fetch main branch
        if: false  # Puedes eliminar este paso si no es necesario
        run: git fetch origin main

      # 3. Encontrar los archivos .strings que han cambiado y generar diffs
      - name: Find changed .strings files and generate diffs
        run: |
          mkdir -p diff_files
          
          git diff --name-only origin/main...HEAD -- '*.strings' | while IFS= read -r file; do
            diff_output="diff_files/$(basename "$file" .strings)_diff.txt"
            git diff origin/main...HEAD -- "$file" > "$diff_output" || true
          done
      
      # 4. Subir los archivos diff como artefacto
      - name: Upload diff files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: strings-diff
          path: diff_files/
