name: 'Test add'

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First number'
        required: true
        default: '40'
      num2:
        description: 'Second number'
        required: true
        default: '60'

jobs:
  add_numbers_job:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Add two numbers
        id: step_add
        uses: ./.github/actions/add_numbers
        with:
          num1: ${{ github.event.inputs.num1 }}
          num2: ${{ github.event.inputs.num2 }}

      - name: Manual write to step output
        id: manual_step
        run: echo '"manual_test=success" >> $GITHUB_STEP_OUTPUT'

      - name: Show manual output
        run: echo "Manual test output: ${{ steps.manual_step.outputs.manual_test }}"

      - name: Show result
        run: echo "The addition is ${{ steps.step_add.outputs.total }}"
